import { ProductItem } from "@/types/pos";

export const initialProductCatalog: ProductItem[] = [
  {
    id: "prod-1",
    name: "Wireless Headphone",
    sku: "ELEC-HD-001",
    category: "Electronics",
    price: 2450,
    priceFormatted: "৳2,450",
    stock: 24,
    image: "/product_images/headphone (1).png",
  },
  {
    id: "prod-2",
    name: "Smart Watch",
    sku: "ELEC-SW-002",
    category: "Electronics",
    price: 3850,
    priceFormatted: "৳3,850",
    stock: 24,
    image: "/product_images/smart_watch.png",
  },
  {
    id: "prod-3",
    name: "Bluetooth Speaker",
    sku: "ELEC-BS-003",
    category: "Electronics",
    price: 1850,
    priceFormatted: "৳1,850",
    stock: 24,
    image: "/product_images/bluetooth speaker.png",
  },
  {
    id: "prod-4",
    name: "USB-C Cable",
    sku: "ELEC-UC-004",
    category: "Electronics",
    price: 250,
    priceFormatted: "৳250",
    stock: 24,
    image: "/product_images/usb_typec.png",
  },
  {
    id: "prod-5",
    name: "Wireless Mouse",
    sku: "ELEC-WM-005",
    category: "Electronics",
    price: 1250,
    priceFormatted: "৳1,250",
    stock: 24,
    image: "/product_images/wireless_mouse.png",
  },
  {
    id: "prod-6",
    name: "Mechanical Keyboard",
    sku: "ELEC-MK-006",
    category: "Electronics",
    price: 1650,
    priceFormatted: "৳1,650",
    stock: 24,
    image: "/product_images/keyboard.png",
  },
  {
    id: "prod-7",
    name: "Smartphone",
    sku: "ELEC-SP-007",
    category: "Electronics",
    price: 750,
    priceFormatted: "৳750",
    stock: 24,
    image: "/product_images/mobile.png",
  },
  {
    id: "prod-8",
    name: "Steel Water Bottle",
    sku: "HOME-WB-008",
    category: "Home & Living",
    price: 450,
    priceFormatted: "৳450",
    stock: 24,
    image: "/product_images/steel_water_bottle.png",
  },
  {
    id: "prod-9",
    name: "Wireless Earbuds",
    sku: "ELEC-WE-009",
    category: "Electronics",
    price: 950,
    priceFormatted: "৳950",
    stock: 24,
    image: "/product_images/wireless_airbuds.png",
  },
];

